# Generated by Django 5.2 on 2025-04-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(default='media/memorial_profile/', upload_to='')),
                ('image_collection', models.ImageField(default='media/memorial_collections/', upload_to='')),
            ],
        ),
    ]
