# Generated by Django 5.2 on 2025-04-10 20:35

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorial',
            name='image',
        ),
        migrations.RemoveField(
            model_name='memorial',
            name='image_collection',
        ),
        migrations.AddField(
            model_name='memorial',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.memorial_image_profile_upload_path),
        ),
        migrations.CreateModel(
            name='MemorialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=myapp.models.memorial_image_collection_upload_path)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.memorial')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
